#!/bin/bash


xsetroot -cursor_name left_ptr
sxhkd &
 
bspc config border_width         3
bspc config top_padding          5
bspc config bottom_padding       42.5
bspc config borderless_monocle   false

bspc config window_gap            10
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config focused_border_color \#D65D0E


# ##############################################################################
# #                                  FUNCTIONS                                 # 
# ##############################################################################
INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="DVI-I-2-1"
# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi

# $HOME/.screenlayout/dual_monitor.sh
bash /home/$USER/.config/bspwm/scripts/dual-monitor.sh

bash /home/$USER/.config/bspwm/scripts/keyring-start.sh

#Load Picom
bash /home/$USER/.config/bspwm/scripts/start-picom.sh

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################

rm $HOME/.cache/dunst.log
rm $HOME/.cache/fake_battery_capacity
rm $HOME/.cache/eww-calendar.lock
rm $HOME/.cache/eww-escreen.lock
rm $HOME/.cache/eww-control-center.lock
rm -r $HOME/.cache/dunst/


# Fix cursor size.
xsetroot -xcf /usr/share/icons/volantes-cursors/cursors/left_ptr 32

sudo nmcli networking off && sudo nmcli networking on && nmcli r all on

